### ISSUE TITLE
Build Issues with Current PIO

### ISSUE THREAD

**Issue by GeorgeIoak** [pilotak/ethernet-relay-temp#1]
I know this project is a bit old but when I tried build it I kept getting errors no matter what I tried. Can you try to compile with an updated install and see if it still compiles for you.

**Comment by pilotak** [comment]
Sure, I will look into it

**Comment by pilotak** [comment]
I could not get the "old" core compiled. So at "new" core I have fixed the ADC error but at the moment i can't get the watchdog compiled.

I have submitted an issue to PIO https://github.com/platformio/platform-ststm32/issues/396

**Comment by GeorgeIoak** [comment]
OK, thanks, I had similar problems but wasn't familiar enough with your code so I'm glad that you found time to check and report an issue to PIO. Hopefully they will reply to your issue in a timely manner.

**Comment by pilotak** [comment]
@GeorgeIoak seems to be fixed in stm-core version 8.0.0 you can check in [actions](https://github.com/pilotak/ethernet-relay-temp/actions?query=workflow%3Abuild).
Feel free to reopen if any problem occur.
